# To implement:
# Increment next number in line (https://github.com/helix-editor/helix/issues/1645).
# Jump to next empty line (https://github.com/helix-editor/helix/issues/1580).
# Indent/unindent in insert mode (https://github.com/helix-editor/helix/issues/334).
# Partial loading of config (https://github.com/helix-editor/helix/issues/1732).
# Fuzzy search in results of a search command, not only in the file names (https://github.com/helix-editor/helix/issues/196).
# Highlight search results (https://github.com/helix-editor/helix/issues/1733).
# Sessions (https://github.com/helix-editor/helix/issues/401).
# Save files for crash (https://github.com/helix-editor/helix/issues/290).
# Line wrapping (https://github.com/helix-editor/helix/issues/136).
# Alert if file changed on disk plus reload (https://github.com/helix-editor/helix/issues/1125).
#
# Indenting (>) adds spaces on empty lines (https://github.com/helix-editor/helix/issues/1642).
# 
# Possibly config:
# Search word under the cursor (instead of words containing the word under the selection).
# Global search of the word under the cursor.
# Remove completed text (by pressing ctrl-p, ctrl-n in cause you don't want any of the completions).
# Ctrl-d to continue scrolling at the end (https://github.com/helix-editor/helix/issues/1731).
# Continue comment when pressing enter in insert mode (https://github.com/helix-editor/helix/issues/1730).
#
# Case sensitive search (smart-case in next version).

theme = "bogster"

[editor]
line-number = "relative"
mouse = false

# [editor.search]
# smart-case = false

[keys.normal]
# Char/line movement
c = "move_char_left"
r = "move_char_right"
t = "move_line_down"
s = "move_line_up"

# Word movement
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"

# Change
l = "change_selection"

# Replace
h = "replace"

# Until
j = "find_till_char"

# Substitute
k = "select_regex"

[keys.normal.space]
w = ":write"
q = ":write-quit-all!"

[keys.normal.z]
p = "scroll_up"
n = "scroll_down"

down = "no_op"
k = "no_op"
j = "no_op"
up = "no_op"

[keys.select]
# Char/line movement
c = "extend_char_left"
r = "extend_char_right"
t = "extend_line_down"
s = "extend_line_up"

# Word movement
"é" = "extend_next_word_start"
"É" = "extend_next_long_word_start"

# Change
l = "change_selection"

# Until
j = "extend_till_char"

# Substitute
k = "select_regex"
