# To implement:
# *** Continue comment when pressing enter in insert mode (https://github.com/helix-editor/helix/issues/1730).
# *** Sessions (https://github.com/helix-editor/helix/issues/401).
# ** Indent/unindent in insert mode (https://github.com/helix-editor/helix/issues/334).
# ** Partial loading of config (https://github.com/helix-editor/helix/issues/1732).
# ** Fuzzy search in results of a search command, not only in the file names (https://github.com/helix-editor/helix/issues/196).
# ** Line wrapping (https://github.com/helix-editor/helix/issues/136).
# ** Alert if file changed on disk plus reload (https://github.com/helix-editor/helix/issues/1125).
# ** Go to matching brackets when cursor is not on bracket (https://github.com/helix-editor/helix/issues/1072).
# ** Save files for crash (https://github.com/helix-editor/helix/issues/290).
# ** File completions (https://github.com/helix-editor/helix/issues/1015).
# ** Ctrl-d to continue scrolling at the end (https://github.com/helix-editor/helix/issues/1731).
# ** Tabline (https://github.com/helix-editor/helix/issues/475).
# * Highlight search results (https://github.com/helix-editor/helix/issues/1733).
# * Alert if cannot write file (https://github.com/helix-editor/helix/issues/1575).
# * Highlight invisible characters (https://github.com/helix-editor/helix/issues/1068).
# * Marks (https://github.com/helix-editor/helix/issues/703).
# Indentation line (https://github.com/helix-editor/helix/issues/1257).
# Customizable statusline (https://github.com/helix-editor/helix/issues/708).
# File diff (https://github.com/helix-editor/helix/issues/405).
# 
# Possibly config:
# *** Search word under the cursor (instead of words containing the word under the selection) (https://github.com/helix-editor/helix/issues/1762) (automate / <C-s>).
# (or maybe even https://github.com/helix-editor/helix/issues/1383)
# *** Global search of the word under the cursor (automate <Space>+/ <C-s>).
# Shortcut to redraw the whole UI.
#
# Already implemented:
# Remove completed text (already possible with ctrl-c).
# Case sensitive search (smart-case in next version).
# Jump to next empty line (https://github.com/helix-editor/helix/issues/753 https://github.com/helix-editor/helix/issues/1580).
# Increment next number in line (https://github.com/helix-editor/helix/issues/1645).
# Indenting (>) adds spaces on empty lines (https://github.com/helix-editor/helix/issues/1642).

theme = "bogster"

[editor]
line-number = "relative"
mouse = false

# [editor.search]
# smart-case = false

[keys.normal]
# "*" = ["search"]

# Char/line movement
c = "move_char_left"
r = "move_char_right"
t = "move_line_down"
s = "move_line_up"

# Word movement
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"

# Change
l = "change_selection"

# Replace
h = "replace"

# Until
j = "find_till_char"

# Substitute
k = "select_regex"

[keys.normal.space]
w = ":write"
q = ":write-quit-all!"

[keys.normal.z]
p = "scroll_up"
n = "scroll_down"

down = "no_op"
k = "no_op"
j = "no_op"
up = "no_op"

[keys.select]
# Char/line movement
c = "extend_char_left"
r = "extend_char_right"
t = "extend_line_down"
s = "extend_line_up"

# Word movement
"é" = "extend_next_word_start"
"É" = "extend_next_long_word_start"

# Change
l = "change_selection"

# Until
j = "extend_till_char"

# Substitute
k = "select_regex"
