# To implement:
# Increment next number in line.
# Sessions.
# Save files for crash.
# Line wrapping (https://github.com/helix-editor/helix/issues/136).
# Fuzzy search in results of a search command, not only in the file names.
# Highlight search results.
# Indenting (>) adds spaces on empty lines.
# Partial loading of config.
# Indent/unindent in insert mode (https://github.com/helix-editor/helix/issues/334).
# 
# Possibly config:
# Remove unused keybindings (like zk).
# Allow <Space>q to exit even when the buffer does not represent a file on disk.
# Jump to next empty line.
# Search word under the cursor (instead of words containing the word under the selection).
# Global search of the word under the cursor.
# Remove completed text (by pressing ctrl-p, ctrl-n in cause you don't want any of the completions).
# Ctrl-d to continue scrolling at the end.
# Continue comment when pressing enter in insert mode.
# Case sensitive search (smart-case in next version).

theme = "bogster"

[editor]
line-number = "relative"
mouse = false

# [editor.search]
# smart-case = false

[keys.normal]
# Char/line movement
c = "move_char_left"
r = "move_char_right"
t = "move_line_down"
s = "move_line_up"
"space" = { w = ":write", q = ":write-quit-all!" }
z = { t = "scroll_down", s = "scroll_up" }

# Word movement
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"

# Change
l = "change_selection"

# Replace
h = "replace"

# Until
j = "find_till_char"

# Substitute
k = "select_regex"
