[manager]
prepend_keymap = [
    # Navigation
    { on = [ "s" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "t" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "S" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = [ "T" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

    { on = [ "<A-s>" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = [ "<A-t>" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },
]
