root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: false
  cliptimeout: 45
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: false
  path: gpgcli-gitcli-fs+file:///home/bouanto/.password-store
  safecontent: true
  usesymbols: true
  notifications: false
mounts: {}
version: 1.7.0
