root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: false
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///home/bouanto/.password-store
  recipient_hash: {}
  safecontent: true
  usesymbols: true
mounts: {}
version: 1.8.0
